### ISSUE TITLE
Vs 2022 support

### ISSUE THREAD

**Issue by kirsan31** [robindegen/vs2019_original_blue_theme#2]
Hi, any plans to add vs 2022 support?
Thanks.

**Comment by robindegen** [comment]
Yes this is very likely. But this will probably happen within a few days when vs2022 is released (not preview).

**Comment by kirsan31** [comment]
@robindegen any news?

**Comment by robindegen** [comment]
Due to personal circumstance I'm not able to work on this; however there is another project that seems to do the same. You can download it here:
https://marketplace.visualstudio.com/items?itemName=MadsKristensen.BlueColorTheme

**Comment by kirsan31** [comment]
> Due to personal circumstance I'm not able to work on this; however there is another project that seems to do the same. You can download it here: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.BlueColorTheme

The internal structure of Mads theme is really different from yours. And it have bugs that's absent in your theme.
I've already ported your theme to vs 2022. So, if your wish, a bit later I can make a P.R...

**Comment by robindegen** [comment]
Aah okay. I would happily accept a PR for this if you're willing to do that; thank you.
